### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by olumide95**
profile1

profile2

### CODE REVIEW

**Comment by Victor-Ugwueze** [comment]
You have more than one file changed

**Comment by olumide95** [comment]
Hi, i only changed one file, thats the clone of template i made. here is a
screenshot of my commit.
[image: commit.PNG]

**Comment by olumide95** [comment]
Clone of the template given i meant.

**Comment by olumide95** [comment]
> You have more than one file changed
Hi, i only changed one file, thats the clone of template i made. here is a
screenshot of my commit.
commit

**Pull request closed without merging**
