### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by an-apluss**
**What PR does?**
- To add my profile page

**Result Screenshot**
The HNG Internship - an-apluss profile page

### CODE REVIEW

**Comment by Victor-Ugwueze** [comment]
You are targeting the wrong branch, you are required to raise a PR against `staging` and not `master`.

Ask your friends on Slack for assistance.

**Comment by an-apluss** [comment]
Add profile picture

**Comment by Victor-Ugwueze** [comment]
You also have made changes to more than one files, try and resolve it in your next submission.

**Comment by an-apluss** [comment]
Kindly, signify the other files I made changes to.

**Pull request closed without merging**
