### PR TITLE
add sammy's profile

### PR DESCRIPTION
**Pull request by Achemsamuel**

### CODE REVIEW

**Comment by Achemsamuel** [comment]
Fixed it!

**Comment by digitalforus** [comment]
Add screenshot

**Comment by digitalforus** [comment]
Add blog link to the sheet by resubmitting the form.

Thanks

**Comment by Achemsamuel** [comment]
I didn't write an article on bugs on timbu or other tests.

**Comment by Achemsamuel** [comment]
or is it just a link to my blog?

**Comment by Achemsamuel** [comment]
So I use a Mac and I use Ampps on it so the UI for the page isn't quite perfect.
I added a random screenshot from someone else's page so you see what I'm talking about.
On a windows system it actually works just fine. I had the same issue last year with HNG 4 anyway and I had to use a friend's HP to prove my point. However, right now I don't have that luxury no more.
Screen Shot 2019-04-07 at 16 51 16
Screen Shot 2019-04-07 at 16 50 40

**Comment by digitalforus** [comment]
You are not doing the right thing man....

**Comment by digitalforus** [comment]
https://github.com/hnginternship5/hng.tech/pull/1120


check that.... Your screenshot should display as that

**Comment by Achemsamuel** [comment]
.... I actually am man, it's not my first time.
This is exactly the same thing I faced during hng4, too bad I don't have anyone with a HP laptop close, would have totally used it. 
I didn't edit the original template files, the CSS files are intact so it definitely can't be anything I did.

**Pull request closed without merging**
