### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by sherifdauda**

### CODE REVIEW

**Comment by sherifdauda** [comment]
/home/sherif/Pictures/Screenshot from 2019-04-03 21-33-41.png

**Comment by sherifdauda** [comment]
Screenshot from 2019-04-03 21-33-41

**Comment by sherifdauda** [comment]
Screenshot from 2019-04-03 21-37-40

**Comment by Victor-Ugwueze** [comment]
You have more than one file change in your PR

**Pull request closed without merging**
