### PR TITLE
Added my profile page: tonyfrenzy.php

### PR DESCRIPTION
**Pull request by tonyfrenzy**
staging branch task

### CODE REVIEW

**Comment by Victor-Ugwueze** [comment]
Profile not found on slack, Send a message if this a mistake

**Comment by tonyfrenzy** [comment]
Sent you a pm on slack.

**Comment by Victor-Ugwueze** [comment]
Raise PR against `staging` and not `master`

Ask your friends if your not sure

**Comment by tonyfrenzy** [comment]
> your friends if your not sure
Done with a new PR:
https://github.com/hnginternship5/hng.tech/pull/624

Line 452 on list

**Pull request closed without merging**
