### PR TITLE
Adding my profile

### PR DESCRIPTION
**Pull request by Cool-sami12**
Cool

### CODE REVIEW

**Comment by digitalforus** [comment]
reupload the screenshot.... It is off-track

**Comment by Cool-sami12** [comment]
Cool


> reupload the screenshot.... It is off-track

ok i have reuploaded it

**Comment by Victor-Ugwueze** [comment]
Ask your friends for assistance, your profile styling is off.

**Comment by chygoz2** [comment]
Profile is distorted.

**Pull request closed without merging**
