### PR TITLE
Marzouq done Adding files. 

### PR DESCRIPTION
**Pull request by MarzouqAli**

### CODE REVIEW

**Comment by Victor-Ugwueze** [comment]
Add screenshot

**Comment by MarzouqAli** [comment]
Screenshot_2019-04-04 The HNG Internship

**Comment by MarzouqAli** [comment]
> Add screenshot

Screenshot_2019-04-04 The HNG Internship

**Comment by MarzouqAli** [comment]
> Add screenshot

I'm waiting for review

**Pull request merged**
