### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by remiljw**
my profile page

### CODE REVIEW

**Comment by Victor-Ugwueze** [comment]
No screenshot

**Comment by chygoz2** [comment]
You should only add your profile page. Your PR has 2 files changed. You also did not upload a screenshot.

**Comment by remiljw** [comment]
I did all you mentioned.. I added a screenshot as you said.. I just viewed
it now

**Comment by remiljw** [comment]
Please I added the screenshot.. That was the 2nd commit

**Comment by Victor-Ugwueze** [comment]
You have more than one files changed.

Ask your friends on Slack for assistance.

**Pull request closed without merging**
