### PR TITLE
Request to Add profile page

### PR DESCRIPTION
**Pull request by AlfredBryan**
Screenshot 2019-04-03 at 6 37 44 PM

### CODE REVIEW

**Comment by digitalforus** [comment]
Add a screenshot

**Comment by AlfredBryan** [comment]
Screenshot added

**Comment by Victor-Ugwueze** [comment]
Go and read the documentation again, you shouldn't touch this file `views/current.php`

**Comment by Victor-Ugwueze** [comment]
Raise PR against staging

**Pull request closed without merging**
