### PR TITLE
ebz.php - first merge

### PR DESCRIPTION
**Pull request by EbunAlabi**

### CODE REVIEW

**Comment by EbunAlabi** [comment]
A merge.

**Comment by Victor-Ugwueze** [comment]
No screenshot.

Ask your friends on Slack for assistance and make another submission.

**Comment by EbunAlabi** [comment]
Screenshot added.

**Comment by EbunAlabi** [comment]
hng screenshot

**Comment by EbunAlabi** [comment]
hng screenshot

**Pull request closed without merging**
