### PR TITLE
Add my profile

### PR DESCRIPTION
**Pull request by Ramadhani99**
Screenshot from 2019-04-07 23-38-16

### CODE REVIEW

**Comment by Ramadhani99** [comment]
Thanks sir
kindly regards

**Comment by Ramadhani99** [comment]
I don't undestand how to intergrate with travis-ci

**Comment by Victor-Ugwueze** [comment]
You are not expected to do any integration

**Comment by Ramadhani99** [comment]
what should i do

**Comment by Ramadhani99** [comment]
what should i do to get green color and make up to stage 2

**Pull request merged**
