### PR TITLE
add my profile

### PR DESCRIPTION
**Pull request by Lord-Jerry**

### CODE REVIEW

**Comment by Victor-Ugwueze** [comment]
Add screenshot

**Comment by Lord-Jerry** [comment]
LJ1
LJ2

**Comment by Lord-Jerry** [comment]
@Victor-Ugwueze  done that

**Comment by Lord-Jerry** [comment]
@alumicheal kindly review

**Comment by Lord-Jerry** [comment]
@alumichael

**Comment by Lord-Jerry** [comment]
@timolinn kindly review

**Pull request merged**
