### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by remiljw**
stage 2

### CODE REVIEW

**Comment by Victor-Ugwueze** [comment]
You have deleted your profile, leaving an image.

**Comment by Victor-Ugwueze** [comment]
Kindly work on this ASAP

**Comment by remiljw** [comment]
``



<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        remiljw
                        <h6>Michael Ajanaku</h6>
                        <p>Front-End Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/iruobe_09" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/remiljw" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@remiljw" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a self-taught Front End Developer based in Lagos,Nigeria. Also a student of Yaba College of Technology studying Mechanical Engineering.<br><br/>
                        I make you stay Glued to your screens.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | CSS | Javascript</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>``

**Comment by remiljw** [comment]
On it

**Comment by remiljw** [comment]
Delete

**Comment by remiljw** [comment]
Delete

**Pull request closed without merging**
