### PR TITLE
Modifications Added

### PR DESCRIPTION
**Pull request by tuck183**

### CODE REVIEW

**Comment by tuck183** [comment]
Added Tochukwu.php in view and edited index page

**Comment by tuck183** [comment]
demo

**Comment by Onibenjo** [comment]
localhost_hng tech-master_views_interns_onibenjo php (1)

**Comment by whizline** [comment]
i have inserted my data
profile

**Comment by badex-ai** [comment]
ok ready to go

**Comment by badex-ai** [comment]
ok ready to go
Ali Hng tech

**Pull request closed without merging**
