### PR TITLE
Add My Profile

### PR DESCRIPTION
**Pull request by abruzy**
hng

### CODE REVIEW

**Comment by giftshaw** [comment]
Gift Henshaw

**Comment by giftshaw** [comment]
https://github.com/hnginternship5/hng.tech/compare/staging...giftshaw:staging

**Comment by digitalforus** [comment]
How many screenshots are you guys adding...
Kindly do the PR separatly....
Thanks

**Comment by abruzy** [comment]
Boss @digitalforus please my name is still red, I have done everything expected of me Sir.

**Pull request closed without merging**
