### PR TITLE
added my profile to hng.tech

### PR DESCRIPTION
**Pull request by phreecodes**

### CODE REVIEW

**Comment by phreecodes** [comment]
I just added my personal profile to hng.tech

**Comment by Victor-Ugwueze** [comment]
No screenshot

**Comment by phreecodes** [comment]
> No screenshot

The new guide does not allow us check the profile page because we are now only supposed to push only one file, which is ourSlackUsername.php so there is no way to get screenshots

**Comment by Victor-Ugwueze** [comment]
Ask your friends for on how to get a screenshot.

No screenshot, no review

**Comment by phreecodes** [comment]
> Ask your friends for on how to get a screenshot.
> 
> No screenshot, no review

Ok... I'll fix that now

**Comment by phreecodes** [comment]
Screenshot (56)

**Pull request merged**
