### PR TITLE
iwakinomotoye

### PR DESCRIPTION
**Pull request by Iwakinomotoye**
hng

### CODE REVIEW

**Comment by Victor-Ugwueze** [comment]
Your profile styling is different

**Comment by Iwakinomotoye** [comment]
Please can i readjust it, and pull the request again? Or its gone? @Victor-Ugwueze

**Comment by Iwakinomotoye** [comment]
Please can i readjust it, and pull the request again? Or its gone already? @Victor-Ugwueze

**Comment by Iwakinomotoye** [comment]
When you say my profile styling, please are you referring to my image, because that is only where I feel i need to work on? @Victor-Ugwueze

**Pull request closed without merging**
